name: new_movie_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  get: ^4.6.5
  json_serializable: ^6.3.1
  logger: ^1.1.0
  retrofit: ^3.0.1+1
  shared_preferences: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0

flutter:

  uses-material-design: true

  assets:
    - assets/logo/
