/// GENERATED BY assets_scanner. DO NOT MODIFY BY HAND.
/// See more detail on https://github.com/littleGnAl/assets-scanner.
class R {
  static const package = 'new_movie_flutter';

  /// ![](/Users/macbookCsi/new_movie/assets/logo/logo_splash.png)
  static const logo_logo_splash = 'assets/logo/logo_splash.png';

  /// ![](/Users/macbookCsi/new_movie/assets/images/splashscreen.png)
  static const images_splashscreen = 'assets/images/splashscreen.png';

  /// ![](/Users/macbookCsi/new_movie/assets/images/slide1.jpeg)
  static const images_slide1 = 'assets/images/slide1.jpeg';

  /// ![](/Users/macbookCsi/new_movie/assets/images/berawan.png)
  static const images_berawan = 'assets/images/berawan.png';

  /// ![](/Users/macbookCsi/new_movie/assets/images/home_background.png)
  static const images_home_background = 'assets/images/home_background.png';

  /// ![](/Users/macbookCsi/new_movie/assets/images/badai.png)
  static const images_badai = 'assets/images/badai.png';

  /// ![](/Users/macbookCsi/new_movie/assets/images/angin.png)
  static const images_angin = 'assets/images/angin.png';

  /// ![](/Users/macbookCsi/new_movie/assets/images/cerahberawan.png)
  static const images_cerahberawan = 'assets/images/cerahberawan.png';

  /// ![](/Users/macbookCsi/new_movie/assets/images/bg_blangko_watermark.png)
  static const images_bg_blangko_watermark = 'assets/images/bg_blangko_watermark.png';

  /// ![](/Users/macbookCsi/new_movie/assets/images/faticon.jpeg)
  static const images_faticon = 'assets/images/faticon.jpeg';

  /// ![](/Users/macbookCsi/new_movie/assets/images/background_onboard.png)
  static const images_background_onboard = 'assets/images/background_onboard.png';

  /// ![](/Users/macbookCsi/new_movie/assets/images/kabut.png)
  static const images_kabut = 'assets/images/kabut.png';

  /// ![](/Users/macbookCsi/new_movie/assets/images/logo.png)
  static const images_logo = 'assets/images/logo.png';

  /// ![](/Users/macbookCsi/new_movie/assets/images/ship_example.png)
  static const images_ship_example = 'assets/images/ship_example.png';

  /// ![](/Users/macbookCsi/new_movie/assets/images/cerah.png)
  static const images_cerah = 'assets/images/cerah.png';

  /// ![](/Users/macbookCsi/new_movie/assets/images/hujan.png)
  static const images_hujan = 'assets/images/hujan.png';

  /// ![](/Users/macbookCsi/new_movie/assets/images/slide2.jpeg)
  static const images_slide2 = 'assets/images/slide2.jpeg';

// ignore_for_file: always_put_control_body_on_new_line,always_specify_types,annotate_overrides,avoid_annotating_with_dynamic,avoid_as,avoid_catches_without_on_clauses,avoid_returning_this,lines_longer_than_80_chars,omit_local_variable_types,prefer_expression_function_bodies,sort_constructors_first,test_types_in_equals,unnecessary_const,unnecessary_new,public_member_api_docs,constant_identifier_names,prefer_double_quotes
}
